ProjectASP/Models/ErrorViewModel.cs
namespace ProjectASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectASP/Models/Karyawan.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectASP.Models
{
    [Table("mst_karyawan", Schema = "dbo")]

    public class Karyawan
    {
        [Key]
        public Guid EmployeeId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Handphone { get; set; }
        public string Email { get; set; }
        public string? Note { get; set; }

    }
}

ProjectASP/Models/Penggajian.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectASP.Models
{
    [Table("mst_penggajian", Schema = "dbo")]
    public class Penggajian
    {
        [Key]
        public Guid GajiId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FullName { get; set; }
        public int Nominal { get; set; }
    }
}

ProjectASP/ViewModels/KaryawanViewModel.cs
namespace ProjectASP.ViewModels
{
    public class KaryawanViewModel
    {
        public Guid EmployeeId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Handphone { get; set; }
        public string Email { get; set; }
        public string? Note { get; set; }
    }
}

ProjectASP/ViewModels/PenggajianViewModel.cs
namespace ProjectASP.ViewModels
{
    public class PenggajianViewModel
    {
        public Guid GajiId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FullName { get; set; }
        public int Nominal { get; set; }
    }
}

ProjectASP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectASP.Models;
using System.Diagnostics;

namespace ProjectASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectASP/Controllers/KaryawanController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectASP.Models;
using ProjectASP.Repositories;
using ProjectASP.ViewModels;

namespace ProjectASP.Controllers
{
    public class KaryawanController : Controller
    {
        private readonly IKaryawanRepository _karyawanRepository;

        public KaryawanController(IKaryawanRepository karyawanRepository)
        {
            _karyawanRepository = karyawanRepository;
        }
        //public IActionResult Index()
        //{
        //    var data = _karyawanRepository.GetAllKaryawan();
        //    return View(data);
        //}

        [HttpGet]
        public async Task<ViewResult> Index()
        {
            var user = new KaryawanViewModel();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Index(KaryawanViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var emp = new Karyawan
                {
                    EmployeeId = viewModel.EmployeeId,
                    EmployeeNumber = viewModel.EmployeeNumber,
                    FullName = viewModel.FullName,
                    Gender = viewModel.Gender,
                    Address = viewModel.Address,
                    Handphone = viewModel.Handphone,
                    Email = viewModel.Email,
                    Note = viewModel.Note
                };
                var result = _karyawanRepository.GetAllKaryawan().Where(c => c.FullName == emp.FullName).FirstOrDefault();
                if (result == null)
                {
                    _karyawanRepository.Tambah(emp);
                    return View(result);
                }
            }
            return View(viewModel);
        }
        public IActionResult Read()
        {
            var data = _karyawanRepository.GetAllKaryawan();
            return View(data);
        }
    }
}

ProjectASP/Controllers/PenggajianController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectASP.Models;
using ProjectASP.Repositories;
using ProjectASP.ViewModels;

namespace ProjectASP.Controllers
{
    public class PenggajianController : Controller
    {
        private readonly IPenggajianRepostory _penggajianRepostory;

        public PenggajianController(IPenggajianRepostory penggajianRepostory)
        {
            _penggajianRepostory = penggajianRepostory;
        }

        [HttpGet]
        public async Task<ViewResult> Index()
        {
            var user = new PenggajianViewModel();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Index(PenggajianViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var emp = new Penggajian
                {
                    GajiId = viewModel.GajiId,
                    EmployeeNumber = viewModel.EmployeeNumber,
                    FullName = viewModel.FullName,
                    Nominal = viewModel.Nominal
                };
                var result = _penggajianRepostory.GetAllPenggajian().Where(c => c.FullName == emp.FullName).FirstOrDefault();
                if (result == null)
                {
                    _penggajianRepostory.Tambah(emp);
                    return View(result);
                }
            }
            return View(viewModel);
        }

        public IActionResult Read()
        {
            var data = _penggajianRepostory.GetAllPenggajian();
            return View(data);
        }

        public IActionResult Json()
        {
           return Json("Hello World");
        }
    }
}

ProjectASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@* <div class="row">
    <div class="col-sm-6">
        <div class="card">
            <div class="card-header">
                Bar Chart
            </div>
            <div class="card-body">
                <meta charset="utf-8" />
                <canvas class="my-4 h-25" id="bar"></canvas>
            </div>
        </div>
    </div>
</div>

<script src="" integrity="sha512-L0Shl7nXXzIlBSUUPpxrokqq4ojqgZFQczTYlGjzONGTDAcLremjwaWv5A+EDLnxhQzY5xUZPWLOLqYRkY0Cbw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
    const chart = document.getElementById('bar').getContext('2d');
    const mychart = new Chart(chart, {
        type = 'bar',
        data = {
            labels : ['001', '002', '003'],
            datasets: [{
                labels : 'Bar Chart',
                data : [100, 200, 300],
                backgroundcolor: 'rgba(6, 128, 250)'
            }]
        },
        options: {
            scales : {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }

    })
</script> *@

<div class="card mb-4">
    <div class="card-header">
        <h3 class="card-title">Sales Value</h3>
    </div>
    <div class="card-body">
        <div id="revenue-chart"></div>
    </div>
</div> <!-- /.card --> <!-- DIRECT CHAT -->
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/apexcharts@3.37.1/dist/apexcharts.min.js" integrity="sha256-+vh8GkaU7C9/wbSLIcwq82tQ2wTf44aOHA8HlBMwRI8=" crossorigin="anonymous"></script> <!-- ChartJS -->
<script>
    $.ajax({
        type: "POST",
        url: "/Penggajian/Json",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function (r) { 
            console.log(r)
        }
    });
    const sales_chart_options = {
        series: [{
            name: "Digital Goods",
            data: [28, 48, 40, 19, 86, 27, 90],
        },
        {
            name: "Electronics",
            data: [65, 59, 80, 81, 56, 55, 40],
        },
        ],
        chart: {
            height: 300,
            type: "bar",
            toolbar: {
                show: false,
            },
        },
        legend: {
            show: false,
        },
        colors: ["#0d6efd", "#20c997"],
        dataLabels: {
            enabled: false,
        },
        stroke: {
            curve: "smooth",
        },
        xaxis: {
            type: "datetime",
            categories: [
                "2023-01-01",
                "2023-02-01",
                "2023-03-01",
                "2023-04-01",
                "2023-05-01",
                "2023-06-01",
                "2023-07-01",
            ],
        },
        tooltip: {
            x: {
                format: "MMMM yyyy",
            },
        },
    };

    const sales_chart = new ApexCharts(
        document.querySelector("#revenue-chart"),
        sales_chart_options,
    );
    sales_chart.render();
</script> <!-- jsvectormap -->

ProjectASP/Views/Karyawan/Index.cshtml
@using ProjectASP.ViewModels

@model KaryawanViewModel
<main class="app-main">
    <!--begin::App Content Header-->
    <div class="app-content-header">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-6">
                    <h5 class="mb-0">Form Karyawan</h5>
                </div>
                @* <div class="col-sm-6">
                    <ol class="breadcrumb sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">
                            Simple Tables
                        </li>
                    </ol>
                </div> *@
            </div> <!--end::Row-->
        </div> <!--end::Container-->
    </div> <!--end::App Content Header--> <!--begin::App Content-->
    <div class="app-content">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-12">
                    <div class="card mb-8">
                        <div class="card-header">
                            <div class="card-title">Form Karyawan</div>
                        </div> <!--end::Header--> <!--begin::Form-->
                        <form asp-action="Index" asp-controller="Karyawan" method="post">
                            <!--begin::Body-->
                            <div class="card-body">
                                <div class="mb-3">
                                    <label for="exampleInputEmail1" asp-for="EmployeeNumber" class="form-label">Employ Number</label> <input asp-for="EmployeeNumber" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                    @* <div id="emailHelp" class="form-text">
                                        We'll never share your email with anyone else.
                                    </div> *@
                                </div>
                                <div class="mb-3"> <label for="exampleInputPassword1" asp-for="FullName" class="form-label">Full Name</label> <input asp-for="FullName" type="text" class="form-control" id="exampleInputPassword1"> </div>
                                <div class="mb-3"> <label for="exampleInputPassword1" asp-for="Email" class="form-label">Email</label> <input asp-for="Email" type="email" class="form-control" id="exampleInputPassword1"> </div>
                                @* <div class="mb-3"> <label for="genderInput" class="form-label">Gender</label> <input type="text" class="form-control" id="genderInput"> </div> *@
                                <div class="mb-3">
                                    <select class="form-select" asp-for="Gender" aria-label="Default select example">
                                        <option disabled selected>--Select Gender --</option>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                    </select>
                                </div>
                                <div class="mb-3"> <label for="addressInput" asp-for="Address" class="form-label">Address</label> <input asp-for ="Address" type="text" class="form-control" id="addressInput"> </div>
                                <div class="mb-3"> <label for="handphoneInput" asp-for="Handphone" class="form-label">Handphone</label> <input asp-for="Handphone" type="text" class="form-control" id="handphoneInput"> </div>
                                <div class="mb-3">
                                    <textarea class="form-control" asp-for="Note" placeholder="Keterangan" id="floatingTextarea2" style="height: 100px"></textarea>
                                </div>
                            </div> <!--end::Body--> <!--begin::Footer-->
                            <div class="card-footer"> <button type="submit" class="btn btn-primary">Submit</button> </div> <!--end::Footer-->
                        </form> <!--end::Form-->
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-6">
                    <h5 class="mb-0">List Table Karyawan</h5>
                </div>
                @* <div class="col-sm-6">
                <ol class="breadcrumb sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                Simple Tables
                </li>
                </ol>
                </div> *@
            </div> <!--end::Row-->
            <br />
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-8">
                        <div class="card-header">
                            <h3 class="card-title">List Table Karyawan</h3>
                        </div> <!-- /.card-header -->
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>Employe Number</th>
                                        <th>Full Name</th>
                                        <th>Gender</th>
                                        <th>Address</th>
                                        <th>Handphone</th>
                                        <th style="width: 40px">Keterangan</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr class="align-middle">
                                        <td>1.</td>
                                        <td>Update software</td>
                                        <td>
                                            <div class="progress progress-xs">
                                                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                            </div>
                                        </td>
                                        <td><span class="badge text-bg-danger">55%</span></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr class="align-middle">
                                        <td>2.</td>
                                        <td>Clean database</td>
                                        <td>
                                            <div class="progress progress-xs">
                                                <div class="progress-bar text-bg-warning" style="width: 70%"></div>
                                            </div>
                                        </td>
                                        <td> <span class="badge text-bg-warning">70%</span> </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr class="align-middle">
                                        <td>3.</td>
                                        <td>Cron job running</td>
                                        <td>
                                            <div class="progress progress-xs progress-striped active">
                                                <div class="progress-bar text-bg-primary" style="width: 30%"></div>
                                            </div>
                                        </td>
                                        <td> <span class="badge text-bg-primary">30%</span> </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr class="align-middle">
                                        <td>4.</td>
                                        <td>Fix and squish bugs</td>
                                        <td>
                                            <div class="progress progress-xs progress-striped active">
                                                <div class="progress-bar text-bg-success" style="width: 90%"></div>
                                            </div>
                                        </td>
                                        <td> <span class="badge text-bg-success">90%</span> </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div> <!-- /.card-body -->
                        <div class="card-footer clearfix">
                            <ul class="pagination pagination-sm m-0 float-end">
                                <li class="page-item"> <a class="page-link" href="#">&laquo;</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">1</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">2</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">3</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">&raquo;</a> </li>
                            </ul>
                        </div>
                    </div> <!-- /.card -->
                </div> <!-- /.col -->
            </div> <!--end::Row-->
        </div>
    </div>
</main>

ProjectASP/Views/Karyawan/Read.cshtml
@model IEnumerable<Karyawan>
<main class="app-main">
    <!--begin::App Content Header-->
    <div class="app-content-header">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-6">
                    <h5 class="mb-0">Form Penggajian</h5>
                </div>
                @* <div class="col-sm-6">
                <ol class="breadcrumb sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                Simple Tables
                </li>
                </ol>
                </div> *@
            </div> <!--end::Row-->
        </div> <!--end::Container-->
    </div> <!--end::App Content Header--> <!--begin::App Content-->
    <div class="app-content">
        <!--begin::Container-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-8">
                        <div class="card-header">
                            <h3 class="card-title">List Table Penggajian</h3>
                        </div> <!-- /.card-header -->
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>Employe Number</th>
                                        <th>Full Name</th>
                                        <th>Gender</th>
                                        <th>Address</th>
                                        <th>Handphone</th>
                                        <th>Email</th>
                                        <th style="width: 40px">Keterangan</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var emp in Model)
                                    {
                                        <tr>
                                            <th>@emp.EmployeeId</th>
                                            <th>@emp.EmployeeNumber</th>
                                            <th>@emp.FullName</th>
                                            <th>@emp.Gender</th>
                                            <th>@emp.Address</th>
                                            <th>@emp.Handphone</th>
                                            <th>@emp.Email</th>
                                            <th>@emp.Note</th>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div> <!-- /.card-body -->
                        <div class="card-footer clearfix">
                            <ul class="pagination pagination-sm m-0 float-end">
                                <li class="page-item"> <a class="page-link" href="#">&laquo;</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">1</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">2</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">3</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">&raquo;</a> </li>
                            </ul>
                        </div>
                    </div> <!-- /.card -->
                </div> <!-- /.col -->
            </div> <!--end::Row-->
      </div>
   </div>
</main>

ProjectASP/Views/Penggajian/Index.cshtml
@using ProjectASP.ViewModels

@model PenggajianViewModel
<main class="app-main">
    <!--begin::App Content Header-->
    <div class="app-content-header">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-6">
                    <h5 class="mb-0">Form Penggajian</h5>
                </div>
                @* <div class="col-sm-6">
                <ol class="breadcrumb sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                Simple Tables
                </li>
                </ol>
                </div> *@
            </div> <!--end::Row-->
        </div> <!--end::Container-->
    </div> <!--end::App Content Header--> <!--begin::App Content-->
    <div class="app-content">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-12">
                    <div class="card mb-8">
                        <div class="card-header">
                            <div class="card-title">Form Penggajian</div>
                        </div> <!--end::Header--> <!--begin::Form-->
                        <form asp-action="Index" asp-controller="Penggajian" method="post">
                            <!--begin::Body-->
                            <div class="card-body">
                                <div class="mb-3">
                                    <label for="exampleInputEmail1" asp-for="EmployeeNumber" class="form-label">Employ Number</label> <input asp-for="EmployeeNumber" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                                    @* <div id="emailHelp" class="form-text">
                                    We'll never share your email with anyone else.
                                    </div> *@
                                </div>
                                <div class="mb-3"> <label for="exampleInputPassword1" asp-for="FullName" class="form-label">Full Name</label> <input asp-for="FullName" type="text" class="form-control" id="exampleInputPassword1"> </div>
                                @* <div class="mb-3"> <label for="genderInput" class="form-label">Gender</label> <input type="text" class="form-control" id="genderInput"> </div> *@
           
                                <div class="mb-3"> <label for="nominalInput" asp-for="Nominal" class="form-label">Nominal</label> <input asp-for="Nominal" type="text" class="form-control" id="nominalInput"> </div>
                            </div> <!--end::Body--> <!--begin::Footer-->
                            <div class="card-footer"> <button type="submit" class="btn btn-primary">Submit</button> </div> <!--end::Footer-->
                        </form> <!--end::Form-->
                    </div>
                </div>
            </div>
            <br />
            
        </div>
    </div>
</main>

ProjectASP/Views/Penggajian/Read.cshtml
@model IEnumerable<Penggajian>
<main class="app-main">
    <!--begin::App Content Header-->
    <div class="app-content-header">
        <!--begin::Container-->
        <div class="container-fluid">
            <!--begin::Row-->
            <div class="row">
                <div class="col-sm-6">
                    <h5 class="mb-0">Form Penggajian</h5>
                </div>
                @* <div class="col-sm-6">
                <ol class="breadcrumb sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                Simple Tables
                </li>
                </ol>
                </div> *@
            </div> <!--end::Row-->
        </div> <!--end::Container-->
    </div> <!--end::App Content Header--> <!--begin::App Content-->
    <div class="app-content">
        <!--begin::Container-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-8">
                        <div class="card-header">
                            <h3 class="card-title">List Table Penggajian</h3>
                        </div> <!-- /.card-header -->
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th style="width: 10px">#</th>
                                        <th>Employe Number</th>
                                        <th>Full Name</th>
                                        <th>Nominal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var emp in Model)
                                    {
                                        <tr>
                                            <th>@emp.GajiId</th>
                                            <th>@emp.EmployeeNumber</th>
                                            <th>@emp.FullName</th>
                                            <th>@emp.Nominal</th>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div> <!-- /.card-body -->
                        <div class="card-footer clearfix">
                            <ul class="pagination pagination-sm m-0 float-end">
                                <li class="page-item"> <a class="page-link" href="#">&laquo;</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">1</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">2</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">3</a> </li>
                                <li class="page-item"> <a class="page-link" href="#">&raquo;</a> </li>
                            </ul>
                        </div>
                    </div> <!-- /.card -->
                </div> <!-- /.col -->
            </div> <!--end::Row-->
        </div>
    </div>
</main>